name: Build
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: 11
          distribution: 'zulu'

      - name: Build the app
        run: ./gradlew build
